project:
  type: website
  output-dir: docs

website:
  title: "Frederick Kwaku Amoakohene"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
      - href: CV.qmd
        text: "{{< fa user-tie >}} CV"
    
    right: 
      - href: Contact.qmd
        text: "{{< fa envelope >}} Contact"
      - href: https://github.com/famoakohene7
        icon: github
      - href: https://www.linkedin.com/in/frederick-amoakohene/
        icon: linkedin

format:
  html:
    theme: flatly
    mainfont: 'Georgia, serif'
    css: styles.css
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    smooth-scroll: true

editor: visual
