project:
  type: website
  output-dir: docs

website:
  title: "Frederick Kwaku Amoakohene"
  navbar:
    background: success
    search: true
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
      - href: CV.qmd
        text: "{{< fa user-tie >}} CV"
      
    right: 
      - href: Contact.qmd
        text: "{{< fa envelope >}} Contact"
      
      - href: https://github.com/famoakohene7
        icon: github
        
      - href: https://www.linkedin.com/in/frederick-amoakohene/
        icon: linkedin


        
        
    

format:
  html:
    theme: simplex
    mainfont: arial
    css: styles.css
    toc: true

editor: visual